### PR TITLE
Fixes TS issue with mismatched type for deprecate

### PR DESCRIPTION
**Pull request by scalvert**
Fixes type mismatch introduced in #272.

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
should an issue be opened to ember-cli-typescript as well?

**Comment by scalvert** [comment]
What specifically do you think that issue should call out?

**Comment by NullVoxPopuli** [comment]
To update https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ember__debug/index.d.ts#L71 to match the current API so that test-waiters can eventually remove the override?

**Comment by scalvert** [comment]
Oh, so that would be in DefinitelyTyped, not `ember-cli-typescript`, right? Also, I believe there's already a PR for this: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52397

**Comment by scalvert** [comment]
I've also further updated the call site for `deprecate` since the `since` property was incorrectly called (it's an object, not a string).

**Review by rwjblue — APPROVED** [review]

**Pull request merged**
