### PR TITLE
Fix a README typo

### PR DESCRIPTION
**Pull request by lukemelia**

### CODE REVIEW

**Comment by scalvert** [comment]
Imagine being async?

**Review by scalvert — APPROVED** [review]

**Comment by scalvert** [comment]
Thanks!

**Comment by lukemelia** [comment]
> Imagine being async?

The backlash to the mindfulness movement? "Simply be present at a moment sometime in the future."

**Comment by scalvert** [comment]
Clearly. That or the modern reboot of a Spike Jones movie about John Malkovich...

**Pull request merged**
